---
- name: update web server
  hosts: webservers

  tasks:
  - name: Install a http pkg
    yum:
      name=http
      state=latest
  - name: Start a http service
    service:
      name=http
      state=restarted

  
