---
- hosts: netscaler
  gather_facts: no
  tasks:
   - name: Setup http service group
     delegate_to: localhost
     netscaler_servicegroup:
      nsip: “{{ nsip }}”
      nitro_user: “{{ nitro_user }}”
      nitro_pass: “{{ nitro_pass }}”
      
      servicegroupname: service-group-http
      servicetype: HTTP
      maxclient: 4000
      servicemembers:
        - ip: 10.10.0.1
          port: 80
          weight: 50
        - ip: 10.10.0.2
          port: 80
          weight: 50
 
 - name: Setup ssl certificate key
   delegate_to: localhost
   netscaler_ssl_certkey:
    nsip: “{{ nsip }}”
    nitro_user: “{{ nitro_user }}”
    nitro_pass: “{{ nitro_pass }}”
    certkey: certificate_http
    cert: server.crt
    key: server.key
 
 - name: Setup lb vserver
   delegate_to: localhost
   netscaler_lb_vserver:
    nsip: “{{ nsip }}”
    nitro_user: “{{ nitro_user }}”
    nitro_pass: “{{ nitro_pass }}”
 
    name: lb-vserver-http
    servicetype: SSL
    ipv46: 10.78.0.1
    port: 443
    ssl_certkey: certificate_http
    servicegroupbindings:
      - servicegroupname: service-group-http
